#!/bin/bash

function singular_number 
{
	if [ "$1" == 0 ]; then
	  ONE_NUMBER=
	fi
	if [ "$1" == 1 ]; then
	  ONE_NUMBER=$2
	fi
  if [ "$1" == 2 ]; then
		ONE_NUMBER=($2$2)
	fi
  if [ "$1" == 3 ]; then
		ONE_NUMBER=($2$2$2)
	fi
  if [ "$1" == 4 ]; then
		ONE_NUMBER=($2$3)
	fi
  if [ "$1" == 5 ]; then
	  ONE_NUMBER=$3
	fi
	if [ "$1" == 6 ]; then
	  ONE_NUMBER=($3$2)
	fi
  if [ "$1" == 7 ]; then
		ONE_NUMBER=($3$2$2)
	fi
  if [ "$1" == 8 ]; then
		ONE_NUMBER=($3$2$2$2)
	fi
  if [ "$1" == 9 ]; then
		ONE_NUMBER=($2$4)
	fi
}

function quota_and_remainder
{
	$QUOTA=$[$1/$2]
	$REMAINDER=$["$1" - $["$QUOTA" * "$2"]]
}

quota_and_remainder $1, 1000
echo $QUOTA
echo $REMAINDER
singular_number $1 I V X
echo $ONE_NUMBER