#!/bin/bash

# hmmm - maybe do this with sed instead..... :-)
function singular_number 
{
  if [ "$1" == 0 ]; then
    ONE_NUMBER=
  fi
  if [ "$1" == 1 ]; then
    ONE_NUMBER=$2
  fi
  if [ "$1" == 2 ]; then
    ONE_NUMBER=($2$2)
  fi
  if [ "$1" == 3 ]; then
    ONE_NUMBER=($2$2$2)
  fi
  if [ "$1" == 4 ]; then
    ONE_NUMBER=($2$3)
  fi
  if [ "$1" == 5 ]; then
    ONE_NUMBER=$3
  fi
  if [ "$1" == 6 ]; then
    ONE_NUMBER=($3$2)
  fi
  if [ "$1" == 7 ]; then
    ONE_NUMBER=($3$2$2)
  fi
  if [ "$1" == 8 ]; then
    ONE_NUMBER=($3$2$2$2)
  fi
  if [ "$1" == 9 ]; then
    ONE_NUMBER=($2$4)
  fi
  if [ "$1" -gt 9 ]; then
    ONE_NUMBER=
  fi	
}

if [ $1 -gt 3000 ]; then
	echo "Argument must be less than 3000"
	exit 1
fi

singular_number $[$1/1000] M
THOUSANDS=$ONE_NUMBER

singular_number $[$1/100%10] C D M
HUNDREDS=$ONE_NUMBER

singular_number $[$1/10%10] X L C
TENS=$ONE_NUMBER

singular_number $[$1%10] I V X
ONES=$ONE_NUMBER

echo $THOUSANDS$HUNDREDS$TENS$ONES